"""track1 initial schema

Revision ID: 61e1977a85b7
Revises: 
Create Date: 2026-08-22 12:05:57.346064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e1977a85b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('kyc_status', sa.Enum('NOT_STARTED', 'PENDING', 'APPROVED', 'REJECTED', name='kycstatus'), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('beneficiaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('preferred_payout_currency', sa.String(), nullable=False),
    sa.Column('relationship_to_sender', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'contact', name='uq_beneficiary_sender_contact')
    )
    op.create_table('kyc_applications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('identification_number', sa.String(), nullable=False),
    sa.Column('residential_address', sa.String(), nullable=False),
    sa.Column('mobile_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('source_of_funds', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='applicationstatus'), nullable=False),
    sa.Column('reviewed_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('xrpl_address', sa.String(), nullable=True),
    sa.Column('xrpl_encrypted_seed', sa.String(), nullable=True),
    sa.Column('rlusd_balance', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('trustline_established', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('remittances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_id', sa.Uuid(), nullable=False),
    sa.Column('zar_send_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fx_rate_used', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('transaction_fee_zar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fx_margin_zar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_converted_zar', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('rlusd_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.Enum('QUOTED', 'CASH_IN_CONFIRMED', 'QUEUED', 'SETTLING', 'SETTLED', 'FAILED', name='remittancestatus'), nullable=False),
    sa.Column('xrpl_tx_hash', sa.String(), nullable=True),
    sa.Column('cash_in_method', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiaries.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('remittance_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('amount_rlusd', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('xrpl_tx_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['remittance_id'], ['remittances.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallet_transactions')
    op.drop_table('remittances')
    op.drop_table('wallets')
    op.drop_table('kyc_applications')
    op.drop_table('beneficiaries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###

    # Hand-added: on Postgres, sa.Enum columns create a standalone CREATE TYPE
    # that DROP TABLE does not remove. Without this, downgrade-then-upgrade on
    # Postgres fails with "type already exists". No-op on SQLite (no real enum
    # type there), so this is safe on both backends.
    bind = op.get_bind()
    sa.Enum(name='remittancestatus').drop(bind, checkfirst=True)
    sa.Enum(name='applicationstatus').drop(bind, checkfirst=True)
    sa.Enum(name='kycstatus').drop(bind, checkfirst=True)
