"""track2 treasury settlement fields

Revision ID: d546f21aa491
Revises: 61e1977a85b7
Create Date: 2026-09-05 00:24:32.680656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd546f21aa491'
down_revision: Union[str, None] = '61e1977a85b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('treasury_batch_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('treasury_settled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remittances', schema=None) as batch_op:
        batch_op.drop_column('treasury_settled_at')
        batch_op.drop_column('treasury_batch_id')

    # ### end Alembic commands ###
